name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Run a command
        run: echo "This job runs every minute"
