name: Run Every 5 Minutes

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Run a command
        run: echo "This job runs every 5 minutes"
