name: Run Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Run a command
        run: echo "This job runs every 5 minutes"
